---

# SPDX-FileCopyrightText: 2021 Robin Schneider <robin.schneider@geberit.com>
#
# SPDX-License-Identifier: CC0-1.0

# Configuration for probot/semantic-pull-requests GitHub check bot
#
# Installation/configuration docs here
# https://github.com/probot/semantic-pull-requests#configuration

scopes:
  - rsyslog
  - filebeat
  - vector
