---
# vim: foldmarker=[[[,]]]:foldmethod=marker

# SPDX-FileCopyrightText: 2021 Robin Schneider <robin.schneider@geberit.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

sources:

  source_internal_logs:
    type: 'internal_logs'
    pid_key: 'process.pid'

transforms:

  transform_int_source_enrich_internal_logs:
    type: remap
    inputs: ['source_internal_logs']
    source: |-
      # Host name should really be part of the log, Vector guys!
      .host.name = downcase(get_env_var("VECTOR_HOSTNAME") ?? get_hostname!())
      .__.event.original = .

      .event.module = "vector"
      .event.dataset = "vector.internal_logs"
