---
# vim: foldmarker=[[[,]]]:foldmethod=marker

# SPDX-FileCopyrightText: 2023 Robin Schneider <ro.schneider@senec.com>
#
# SPDX-License-Identifier: CC0-1.0

api:
  enabled: true
  address: '127.0.0.1:8686'
