---
# vim: foldmarker=[[[,]]]:foldmethod=marker

# SPDX-FileCopyrightText: 2022 Robin Schneider <ro.schneider@senec.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

# This file serves as example only. When using the framework, you are intended
# to copy and modify your copy of this file to your own needs.

api:
  enabled: true
  address: '127.0.0.1:8686'


sources:

  source_socket_syslog_opnsense:
    type: socket
    address: 0.0.0.0:5514
    max_length: 102400
    mode: tcp

  # For new logs. It will use best effort log parsing.
  source_socket_syslog_other:
    type: socket
    address: 0.0.0.0:5515
    max_length: 102400
    mode: tcp

  source_logstash_any:
    type: logstash
    address: 0.0.0.0:5044

  source_vector_any:
    type: vector
    address: 0.0.0.0:9000
    version: "2"

transforms:

  transform_pre_source_enrich_socket_syslog_opnsense:
    type: remap
    inputs:
      - 'source_socket_syslog_opnsense'
    source: |-
      .event.module = "opnsense"

  transform_source_enrich_socket_syslog:
    type: remap
    inputs:
      - 'source_socket_syslog_other'
      - 'source_logstash_any'
      - 'source_vector_any'
      - 'transform_pre_source_enrich_socket_syslog_*'
    source: |-
      .host.ip = .host.name
      .event.created = del(."@timestamp")

sinks:

  sink_kafka:
    type: 'kafka'
    inputs:
      - 'transform_source_enrich_socket_syslog'
      - 'transform_int_source_enrich_internal_logs*'
    bootstrap_servers: '127.0.0.1:9092'

    # Send the same host.name to the same partition.
    key_field: 'host.name'

    topic: 'log-type-{{ event.module }}'
    encoding:
      # Switch to Vector native binary serialization once it is production ready.
      # https://vector.dev/highlights/2022-03-31-native-event-codecs/
      codec: json
