---
# vim: foldmarker=[[[,]]]:foldmethod=marker

# SPDX-FileCopyrightText: 2021 Aswath N Srinivasan <asns@shi-gmbh.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

transforms:
  transform_module_checkmk:
    type: remap
    inputs:
      - 'transform_route_to_module.checkmk'
    source: |-
      .ecs.version = "1.11.0"
      .event.kind = "event"

      .event.original = .message
      if (exists(.__)) {
        .__.fingerprint_inputs = push!(.__.fingerprint_inputs, .event.original)
      } else {
        # Module called from isolated unit test.
        .__.parse_failures_short = []
        .__.parse_failures = []
        .__.parse_warnings_short = []
        .__.parse_warnings = []
      }


      parsed_message, err = parse_grok(.message, "%{TIMESTAMP_ISO8601:timestamp_iso}\\s\\[%{NONNEGINT:event.severity}\\]\\s\\[%{WORD:process.name}(?:\\s%{NONNEGINT:process.pid})?\\]\\s*%{DATA:message}\\s*$")

      if err != null {
        .__.parse_failures_short = push(.__.parse_failures_short, "parse_failure, grok")
        .__.parse_failures = push(.__.parse_failures, "parse_failure, grok: " + err)

        # checkmk.audit parsing [[[
        if (match(.event.dataset, r'^checkmk.audit$')) {
          parsed_audit_message, err_audit = parse_grok(.message, "%{DATA:timestamp_s} (?:- %{DATA:user.name}\\s+%{DATA:event.action}\\s+)?%{GREEDYDATA:message}$")
         if err_audit != null {
           .__.parse_failures_short = push(.__.parse_failures_short, "parse_failure, audi_grok")
           .__.parse_failures = push(.__.parse_failures, "parse_failure, audt_grok: " + err_audit)
         } else {
           . |= parsed_audit_message
           ."@timestamp" = to_timestamp!(del(.timestamp_s))
           .event.action = del(."event.action")
           .user.name = del(."user.name")
         }
        }
        # ]]]

      } else {
        # Timestamp parsing [[[
        parsed_timestamp, err_timestamp = if (!is_nullish(parsed_message.timestamp_iso)) {
          parse_timestamp(parsed_message.timestamp_iso, format: "%Y-%m-%d %T")
        }
        if err_timestamp != null {
          .__.parse_failures_short, err = push(.__.parse_failures_short, "parse_failure: @timestamp parsing")
          .__.parse_failures, err = push(.__.parse_failures, "parse_failure: @timestamp parsing: Could not parse @timestamp. " + err_timestamp)
        } else {
          ."@timestamp" = parsed_timestamp
        }
        # ]]]

        .event.severity, err = parse_int(parsed_message."event.severity")
        .process.name = parsed_message."process.name"
        .process.pid, err = parse_int(parsed_message."process.pid")
        .message = parsed_message.message

        # .message parsing [[[
        if (contains(parsed_message.message, "Executing external command")) {
          if (contains(parsed_message.message, "HOST NOTIFICATION")) {
            parsed_inner_message, err = parse_grok(parsed_message.message, "^Executing external command:\\s*LOG;HOST NOTIFICATION:\\s*(?<contact>[^;]+?);\\s*(?<observer.hostname>[^;]+?);\\s*(?<monitor.status>[^;]+?);\\s*(?<alarm_type>[^;]+?);%{GREEDYDATA:inner_message}$")
            if err != null {
              .__.parse_failures_short = push(.__.parse_failures_short, "parse_failure, inner_message_grok")
              .__.parse_failures = push(.__.parse_failures, "parse_failure, inner_message_grok: " + err)

            } else {
              . |= parsed_inner_message
            }
          } else if (contains(parsed_message.message, "SERVICE NOTIFICATION")) {
            parsed_inner_message, err = parse_grok(parsed_message.message, "^Executing external command:\\s*LOG;SERVICE NOTIFICATION:\\s*(?<contact>[^;]+?);\\s*(?<observer.hostname>[^;]+?);\\s*(?<service.name>[^;]+?);\\s*(?<monitor.status>[^;]+?);%{GREEDYDATA:inner_message}$")
            if err != null {
              .__.parse_failures_short  = push!(.__.parse_failures_short, "parse_failure, inner_message_grok")
              .__.parse_failures = push!(.__.parse_failures, "parse_failure, inner_message_grok: " + err)

            } else {
              . |= parsed_inner_message
            }
          }
          if (is_nullish(.contact)) {
            del(.contact)
          } else {
            .checkmk.cmc.contact, err = split(del(.contact), ",")
            }
          if (is_nullish(."observer.hostname")) { del(."observer.hostname") } else { .observer.hostname = del(."observer.hostname") }
          if (is_nullish(."service.name")) { del(."service.name") } else { .service.name = del(."service.name") }
          if (is_nullish(."monitor.status")) {
            del(."monitor.status")
          } else {
            .checkmk.cmc.monitor.status = del(."monitor.status")
            monitor_status_to_event_severity = {
               "CRITICAL" : 2,
               "WARNING" : 4,
               "OK" : 5,
               "UP" : 5,
               "DOWN" : 4
            }
            .event.severity, err = get(monitor_status_to_event_severity, path:[.checkmk.cmc.monitor.status])
            if err != null {
              .__.parse_warnings_short, err = push(.__.parse_warnings_short, "parse_warning: event.severity")
              .__.parse_warnings, err = push(.__.parse_warnings, "parse_warning: event.severity: Could not get() .checkmk.cmc.monitor.status. " + err)
            }
          }
          if (is_nullish(.alarm_type)) { del(.alarm_type) } else { .checkmk.cmc.alarm_type = del(.alarm_type) }
          .message = del(.inner_message)
          .event.kind = "alert"
        }
        # ]]]

      }
