---

# SPDX-FileCopyrightText: 2022 Robin Schneider <ro.schneider@senec.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

# Installing the dependencies takes ~3 minutes so supporting this without a
# pre-build image seems pointless. Nobody wants to wait 3 minutes for the CI
# test suite when it can run in 10 seconds.
# .test:
#   image: ubuntu:20.04

.test_with_prebuild_container_image:
  image: $EVENT_PROCESSING_FRAMEWORK_DOCKER_IMAGE
  before_script:
    - 'git config --global user.email "you@example.com"'
    - 'git config --global user.name "Your Name"'
  script:
    - 'make test-all docs-full'
  artifacts:
    name: '$CI_JOB_NAME'
    paths:
      - 'docs/*.svg'
