---

# SPDX-FileCopyrightText: 2022 Robin Schneider <ro.schneider@senec.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

.test:
  image: ubuntu:20.04
  before_script:
    - apt-get -qq update && apt-get -qq install -y extrepo
    - extrepo enable vector
    - apt-get -qq update
    - DEBIAN_FRONTEND=noninteractive apt-get -qq install -y vector yamllint bash git make rsync jq gron tzdata python3 python3-yaml graphviz
    - ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
  script:
    - 'make test'

.test_with_prebuild_container_image:
  image: $EVENT_PROCESSING_FRAMEWORK_DOCKER_IMAGE
  script:
    - 'make test'
